# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kG4-NqpEENnZQ_FNS6ImcoZMljCT3ueK
"""

a = int(input())
    if a == 1:
      print("январь")
    elif a == 2:
      print("февраль")
    elif a == 3:
      print("март")
    elif a == 4:
      print("апрель")
    elif a == 5:
      print("май")
    elif a == 6:
      print("июнь")
    elif a == 7:
      print("июль")
    elif a == 8:
      print("август")
    elif a == 9:
      print("сентябрь")
    elif a == 10:
      print("октябрь")
    elif a == 11:
      print("ноябрь")
    elif a == 12:
      print("декабрь")

"""1 задание"""

a = int(input())
if a % 2 == 0:
  print("четное")
else:
  print("нечетное")

"""задание 2"""

N = int(input())
if N > 40:
  print("stonks")
else:
  print("not stonks")

"""задание 3"""

def is_year_leap(year):
  if year % 4 == 0:
    return True
  else:
    return False
a = is_year_leap(int(input()))
print(a)

"""зад 4"""

def is_prime(a):
  if a < 2:
    return False
  for Delitel in range(2, int(a**0.5 + 1)):
    if a % Delitel == 0:
      return False
  else:
    return True
print(is_prime(int(input())))

"""зад 5"""

a = float(input())
b = float(input())
if (a / b >= 3.6) or ((b > abs((-138 / 2) ** 1.3)) and b < (abs((-69 / 28 ** 5.1) * 4))):
    a,b = b,a
print(a)
print(b)

"""зад 6"""

a = int(input())
b = int(input())
c = int(input())
d = int(input())
e = int(input())
cnt = 0
cnt1 = 0
cnt2 = 0 
if a!=b!=c!=d!=e:
  print(True)
if a % 2 == 0:
  cnt += 1
if b % 2 == 0:
  cnt += 1
if c % 2 == 0:
  cnt += 1
if d % 2 == 0:
  cnt += 1 
if e % 2 == 0:
  cnt += 1
print(cnt)
if a < 0:
  cnt1 += 1
if b < 0:
  cnt1 += 1
if c < 0:
  cnt1 += 1
if d < 0:
  cnt1 += 1 
if e < 0:
  cnt1 += 1
print(cnt1)
if a >= -256 and a <= 1024:
  cnt2 += 1
if b >= -256 and b <= 1024:
  cnt2 += 1
if c >= -256 and c <= 1024:
  cnt2 += 1
if d >= -256 and d <= 1024:
  cnt2 += 1
if e >= -256 and e <= 1024:
  cnt2 += 1   
print(cnt2)

"""зад 7"""