# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15_e-36_fQqFrfnvgqWoSOAFBzCVJQ5q-
"""

a = 5
b = int(input())
print(a*b)

"""задание 1"""

a = int(input())
b = int(input())
print((a+b)**2)

"""задание 2

"""

a = 15
b = 10 
c = int(input())
print((a+b)//c)

"""задание 3"""

a = int(input())
b = int(input())
print((a+b)**2)

"""задание 4"""

a = int(input())
b = int(input())
c = int(input())
h = a*b//c
print((1/2*a*h),(a+b+c))

"""задание 5"""

a = int(input())
b = int(input())
print(((a**3+14)/5)*b)

"""задание 6"""

a = int(input())
n = int(input())
print((a**2)//n)

"""задание 7"""

a = float(input())
b = float(input())
print(a//b)
a = int(input())
b = int(input())
print(a*b)
a = int(input())
b = int(input())
print(a%b)

"""задание 8"""

n = int(input())
print(n//(60*60*24), (n//(60*60)), (n//60))

"""задание повышенной 1"""

n = int(input())
print(n+n*n+n*n*n)

"""задание 2"""