# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Erc8ZKRZKaiGoAgPoEOR3Re8POf6pboa
"""

from sklearn.linear_model import LinearRegression as LR
import matplotlib.pyplot as plt
import numpy as np
farengeit = [[-67.0],[-34.0], [0], [34.0], [54.0], [67.0], [100.0]]
kelvin = [[-55.0], [-36.6], [-17.7], [1.1], [12.2], [19.4], [37.7]]
lr = LR()
lr.fit(farengeit, kelvin)
lr.predict([[256], [123]])
lr.coef_
lr.intercept_
farengeit_test = [[-20], [-19.9], [-1.7], [2], [15.7], [20.2], [32.1]]
kelvin_test= lr.predict(farengeit_test)
kelvin_test
for f,k in zip(farengeit_test, kelvin_test):
  print('Фаренгейт', f, '   Кельвин', k)
x_range = np.arange(-70,120)
y_range = x_range*1.8+32 
plt.figure(figsize=(15,8), dpi=280)
plt.plot(x_range, y_range, label='уравнение', linewidth='2')
plt.scatter(farengeit_test, kelvin_test, label='предсказанное значение', color='blue');
plt.xlabel('Фаренгейта')
plt.ylabel('Кельвина')
plt.legend()
plt.grid(True)
plt.show()

"""https://github.com/grandmaser/--311#--311"""

import matplotlib.pyplot as plt
import numpy as np
x = np.arange(-10, 10.01, 0.01)
plt.plot(x, 2*x**2)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.arange(-10, 10.01, 0.01)
plt.plot(np.cos(x))

import matplotlib.pyplot as plt
import numpy as np
x = np.arange(-10, 10.01, 0.01)
plt.plot(x, x**3)

import math as mt
print("2.718281828459045 =",mt.e)
print("3.141592653589793 =",mt.pi)
print("nan =",mt.nan)
print("479001600! =",mt.factorial)
print("4 =",mt.gcd)